### ISSUE TITLE
Create a user guide documentation

### ISSUE THREAD

**Issue by deangelisdf** [deangelisdf/write2audiobook#16]
Need to create a blog something similar to explane how to use the tool and how contribute

**Comment by greg-martinez44** [comment]
Hi,

I just found this project and I like the idea. I saw in the README that you're open to contributors. Can I help with this?

**Comment by deangelisdf** [comment]
Hi @greg-martinez44, yes.

Please Remember to explain the following topics:
- user guide
- development guide (It Is good also only a stub for now)
- how to contribute to It
- license

Desiderable: at the end please if you have feedback to simplify the usage of tool report here. It can be useful.
