### ISSUE TITLE
(tool) move constante to libraries

### ISSUE THREAD

**Issue by deangelisdf** [deangelisdf/write2audiobook#22]
As `BACK_END_TTS` Need to be move to m4b.py, maybe also other constante global Need to be moved to library.

This Activity Need to reduce duplicate code.

**Comment by emadellaloggia** [comment]
download
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by deangelisdf** [comment]
@greg-martinez44 thanks to him, we close It.
